_format_action_invocation  # unused function (src/nasty_utils/_util/argparse_.py:24)
_.log_level  # unused attribute (src/nasty_utils/logging.py:80)
_.log_format  # unused attribute (src/nasty_utils/logging.py:81)
_.log_cli_level  # unused attribute (src/nasty_utils/logging.py:87)
pytest_configure  # unused function (tests/conftest.py:23)
